menu:
- {name: 'Featured Things?? idk what to call this', url: '/featured'}
- {name: 'Curriculum Vitae', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/emcarver'}
- {icon: 'linkedin', link: 'https://ca.linkedin.com/in/emily-carver-387694363'}

contacts:
- {name: 'Emily Carver', institution: 'University of Lethbridge', institution_address: '4401 University Dr W, Lethbridge, AB T1K 3M4', email: 'e.carver@uleth.ca', image: 'assets/img/contact.jpg'}
