menu:
- {name: 'About Me', url: '/aboutme'}
- {name: 'Projects', url: '/projects'}
- {name: 'Curriculum Vitae', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/emcarver'}

contacts:
- {name: 'Emily Carver', institution: 'Lethbridge', institution_address: 'AB', email: 'e.carver@uleth.ca or emily.carver04@gmail.com', image: 'assets/img/campusmorning.jpg'}
